# Generated by Django 6.0.1 on 2026-01-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_discription',
            new_name='receipe_description',
        ),
    ]
